sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- 8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install -g angular-cli-ghpages
script:
- npm run example:lint
- npm run example:e2e
- npm run lint
- npm run test
- npm run example:build-pages
- npm run build
after_success:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  angular-cli-ghpages --dir="dist-ghpages" --repo="https://${GH_TOKEN}@github.com/siegerx3/angular-tinymce.git"
  --name="Sr. Travis" --email="hi@travis.org"; fi
before_deploy:
- cd dist/angular-tinymce
deploy:
  provider: npm
  email: siegerx3-games@yahoo.de
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: JKKyPhE3+gtfKSF0MIo3hVyOFFMG8FDWqRQ1DwMAY5Mz4pH0Zs3yq5oW8DZQ8jgPJ1KihTNveID//V1ygn1AI3j9suLBOPDN2sNTWl1pxUGUB0iM+xSsryiJEgIECXUPiqD+Q16LmFLNfjSdnjsb4nhQxLw1JVs1HB/T7/2UA/1qBQQYEDpDQBTC41crX+kEfmblBDIeqX9eSiQdvFP3/aajrC5x/ZAMQeqEgAyFYNOlHmYKzPaQ45JY9t+uF4mZqfde9ZXsEev6rONfqRJbv2Lw/V+gYBo1kPlaBJTkZD5D/5ZzNBut2Rjxt+vj5OKZLY2QN/5X/YO/Pmeu3h8uTWFxc4/SVbaDox3fEjfmxSd/SLQ/lLbpYUn7p8RSvVdahP8ipe03vMAJOJQNCGHIXL4PEuoVFHSxkfTiKO4gl6fWKwFxLnywNsZj/qlCBocBDQl57lwcLvA9wwcwu9RTHnCJwayxZbh1q1OuWjmrMgPY29V8o8YLw3+YqWFu1lYjYt4t2fjdpKzfcLQ/dLycL6uZ7EPCjoNmMawtX11FJ+mY/GsOuWc8FBhGXi6uwu8YpT8Omiu0Yd6bbPorkX234kCSNVU76BK7eq6yLPHByD0KC2BjIIp22UbebgS+C25fJ6Z0Ol4rNsy3D6PZwqVfxTCPx827W5+9VeRvzZIZGEk=
env:
  global:
    secure: PMDdT00eY/MzAlVPISmMzDb0ZXqSD5k+e2rvGBCDkVJeTBLcdgEck2E/hNxeTd8Ly+eYzbBJS/spfVQtaUzr+8x23p181Sn6WF8di+1zFwthSTlCN0dOvF00M7jnMak42MWYNUQiMa2RhcxzOt9rgbgYDYiAPddSBqfh34Z9pQMDoO27Lhj+dze5DI1bZ7Rnps63Lu1vLNDKY4W5k+3a0mTGwHOj6YS4VpWeQzx/tl78i3YrzlF9S9gt/jgKIL02qDgtU8s/5S0LClR+mnlbupTCy3vxRg/4wUvbz1hZQPbV141e4x5c8UFkF3iL/UXjErtD44ywKFZ7olAsN2XlOH7WESldzAqqnGzrKjhF7HGVu6+ajSnyTJTZcuRM0p2nb+7HgNFOAByS1UyafqgLVo7Ec7mAE815JjJRbetRsw/1xODT/wmUjusjq9WP9OhYpqBcbBrE2CWw+kbKphyrQrWNa3677S0cHY8lrpJSsEA28VKiEB554IVKhORVYaEu7T7fDcu5hMgQuxzZl33sYJxuylhUX8Ga5fjus3MeqzAy/v+brI1Zk7uDyT9W/C0l6gXROeuHrxF8BVW+9AkDFGvfw5IaFibLKcNDY1znQb1PbpTN7OSk6WuJ3/YW8bz5hhP/etpNcubPZxZ97sh3PGdwWOb11Xxw/SZ9iHY4H5U=
