sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- 8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install -g angular-cli-ghpages
script:
- npm run test
- npm run e2e
- npm run build
- npm run build-ghpages
after_success:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  angular-cli-ghpages --dir="dist-ghpages" --repo="https://${GH_TOKEN}@github.com/siegerx3/angular-tinymce.git"
  --name="Sr. Travis" --email="hi@travis.org"; fi
before_deploy:
- cd dist
deploy:
  provider: npm
  email: siegerx3-games@yahoo.de
  api_key:
    secure: NgzUzr5qTicQX4cj2+aTDr7Gx49FFIqyVh1R34b7sk/16sSXGPPIUU+yoLoIyxb8+aP17d3VEA6O/guwbIzHvFGX56LZUfHdkUtxFn9O1YFQxW5/1v2Mf1L1mtPUiQT+UoYH5Fe4zmsSjGCyBHtUa8h1szsqsbG10adYnYBSphQM0ftl0xo7YU/7hrG5SuY4SyfKAqXbc9rITqCps3bSEApHsRwhjEXgsmI01YuwXeusV89DndgUahzNjAFATssrzGVF6B2zaGncefHvYqesvw26U+KvY88ZIl0z1aItdtFG6w+11ssouwjRoo6JXHx9RMVSnzKGeYudVz4YDwQnesIVl7Nmmgz4VpL0ig57YUEnXTETy3Z5TbIfRzl3O5Tohs4loi8PeGXXenqNqU4LLJMs4h3+wZFu2vK6Bl84ftJ9DEUiEPo21tvnUADirdJ+TcO5dKRHgWEQht9MMwfa1nqfgmLohmIwBGHm219Qn7L0wAApRbHEih8z3ZMYZhuMsaJf4aMxTWB2pohdAdTq8TorGl4aJR0GBb+iCIklT5s/CtxYFrHeTEdE5BlGpc1Cs1hl160HkT8mPaCeCQxGIkWTuFBlEIYyb3eKCLn2jpT7sUVVoRavs7ZWpPv2INw6vyYEtZDnBzZs+cAe5IM76Vyk8AoyXuWFUjeu8y6onKc=
  on:
    branch: master
  skip_cleanup: true
env:
  global:
    secure: PMDdT00eY/MzAlVPISmMzDb0ZXqSD5k+e2rvGBCDkVJeTBLcdgEck2E/hNxeTd8Ly+eYzbBJS/spfVQtaUzr+8x23p181Sn6WF8di+1zFwthSTlCN0dOvF00M7jnMak42MWYNUQiMa2RhcxzOt9rgbgYDYiAPddSBqfh34Z9pQMDoO27Lhj+dze5DI1bZ7Rnps63Lu1vLNDKY4W5k+3a0mTGwHOj6YS4VpWeQzx/tl78i3YrzlF9S9gt/jgKIL02qDgtU8s/5S0LClR+mnlbupTCy3vxRg/4wUvbz1hZQPbV141e4x5c8UFkF3iL/UXjErtD44ywKFZ7olAsN2XlOH7WESldzAqqnGzrKjhF7HGVu6+ajSnyTJTZcuRM0p2nb+7HgNFOAByS1UyafqgLVo7Ec7mAE815JjJRbetRsw/1xODT/wmUjusjq9WP9OhYpqBcbBrE2CWw+kbKphyrQrWNa3677S0cHY8lrpJSsEA28VKiEB554IVKhORVYaEu7T7fDcu5hMgQuxzZl33sYJxuylhUX8Ga5fjus3MeqzAy/v+brI1Zk7uDyT9W/C0l6gXROeuHrxF8BVW+9AkDFGvfw5IaFibLKcNDY1znQb1PbpTN7OSk6WuJ3/YW8bz5hhP/etpNcubPZxZ97sh3PGdwWOb11Xxw/SZ9iHY4H5U=
